name: Deploy Marketing Site

on:
  push:
    branches: [ master ]

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      S3_BUCKET: altiora-marketing-site
      CLOUDFRONT_DIST_ID: ${{ secrets.CF_MARKETING_DIST_ID }}
      AWS_ROLE_ARN: ${{ secrets.OIDC_ROLE_ARN }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.6.0'

      - name: Install dependencies
        run: npm install --prefix website

      - name: Build Astro site
        run: npm run build --prefix website

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.3.0
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync website/dist/ s3://${{ env.S3_BUCKET }} --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_DIST_ID }} --paths "/*"
