name: Terraform (Marketing Infra)

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'terraform/marketing/**'
  push:
    branches: [ master ]
    paths:
      - 'terraform/marketing/**'

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_CLOUD_ORGANIZATION: "ALTIORA"
      TF_WORKSPACE: "Altiora-website"
      CONFIG_DIRECTORY: "./terraform"
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.4"
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}

      # If you're using Terraform Cloud's remote backend, use the TFC workflow actions.
      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: upload
        with:
          organization: ${{ env.TF_CLOUD_ORGANIZATION }}
          workspace:    ${{ env.TF_WORKSPACE }}
          directory:    ${{ env.CONFIG_DIRECTORY }}

      - name: Create Plan Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: plan
        with:
          organization:          ${{ env.TF_CLOUD_ORGANIZATION }}
          workspace:             ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
          message: "Plan (marketing) from ${{ github.sha }}"

      - name: Show Plan Summary
        uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.0.0
        with:
          organization: ${{ env.TF_CLOUD_ORGANIZATION }}
          plan:         ${{ fromJSON(steps.plan.outputs.payload).data.relationships.plan.data.id }}

      - name: Apply (master only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.0
        with:
          organization: ${{ env.TF_CLOUD_ORGANIZATION }}
          run:          ${{ steps.plan.outputs.run_id }}
